<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>SpeedTracker</AssemblyName>
    <RootNamespace>SpeedTracker.Windows</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>SpeedTracker.Windows.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SpeedTracker.Core/SpeedTracker.Core.csproj" />
    <ProjectReference Include="../SpeedTracker.Proxy/SpeedTracker.Proxy.csproj" />
  </ItemGroup>
</Project>
