<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SpeedTracker.Core/SpeedTracker.Core.csproj" />
    <ProjectReference Include="../SpeedTracker.Proxy/SpeedTracker.Proxy.csproj" />
  </ItemGroup>
</Project>
